version: "3"
services:
  redis:
    image: bitnami/redis:5.0.9
    ports:
      - '6379:6379'
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ${PERSISTENT_DIR}/data:/bitnami/redis/data